<?php
$customMenu = array();

// add the menu entries here, like these examples
// $customMenu[] = array
// (
//   'link'   => 'the_link.php', // mandatory, without parameters (query string)
//   'title'  => 'My timeline', // mandatory
//   'params' => 'anyParam=anyValue' // optional
// );
// $customMenu[] = array
// (
//   'link'   => 'timeline.php',
//   'title'  => 'My timeline with custom title',
//   'params' => ''
// );
// $customMenu[] = array
// (
//   'link'   => 'timeline_single.php',
//   'title'  => 'Trello example board: Lifestyle Goals (ends Mar. 2016)',
//   'params' => 'board=56718f9d250f10c81e29cc8f'
// );
// $customMenu[] = array
// (
//   'link'   => 'timeline_multiple.php',
//   'title'  => 'Trello example board: Lifestyle Goals and Spring Cleaning (ending Mar. 2016)',
//   'params' => 'boards=5478d8dd7e0d68570bbeb599,56718f9d250f10c81e29cc8f'
// );
?>